env:
  browser: true
  commonjs: true
  es6: true
extends: 'airbnb-base'
parserOptions:
  sourceType: module
rules:
  no-tabs:
    - off
  arrow-body-style:
    - error
    - always
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - warn
    - local

  key-spacing: [1, { "align": "colon" }]
